server {
  listen 80;
  server_name _;
  absolute_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location = /playground {
    return 301 /playground/;
  }

  location /playground/ {
    try_files $uri $uri/ /playground/index.html;
  }

  location / {
    # Next static export writes docs pages as extensionless routes backed by .html files,
    # so nginx needs to try "$uri.html" before falling back to the homepage.
    try_files $uri $uri/ $uri.html /index.html;
  }
}
